## BIBLIOTECAS

In [8]:
import pandas as pd
import numpy as np
from tabulate import tabulate
from IPython.display import Math


## FUNÇÕES

In [9]:
def print_latex(eq):
    return display(Math(eq))

## ALGORITMO

In [10]:
matrizDosCoeficientes = np.array([[12,-1,-1],[-1,12,-2],[-1,-2,12]]).astype(float) #<-------- insira a matriz dos coeficiente aqui
matrizDasVariaveis = []
matrizResultante = np.array([[10],[9],[14]]).astype(float) #<---------------------------insira a matriz resultante aqui

#inserindo operadores para representação matricial
caracterEspace1 = np.array(["*"])
caracterEspace2 = np.array(["="])

#ajusta elementos para o print
for i in range(len(matrizDosCoeficientes)):
    caracterEspace1 = np.insert(caracterEspace1,0,'​')
    caracterEspace2 = np.insert(caracterEspace2,0,'​')
    matrizDasVariaveis.append(["x{}".format(i+1)])

tabela = [[tabulate(matrizDosCoeficientes, tablefmt='heavy_grid'),tabulate(caracterEspace1,tablefmt='plain'), tabulate(matrizDasVariaveis, tablefmt='heavy_grid'), tabulate(caracterEspace2,tablefmt='plain'), tabulate(matrizResultante, tablefmt='heavy_grid')]]
print(tabulate(tabela, headers=[], tablefmt='plain'))

┏━━━━┳━━━━┳━━━━┓  ​   ┏━━━━┓  ​   ┏━━━━┓
┃ 12 ┃ -1 ┃ -1 ┃  ​   ┃ x1 ┃  ​   ┃ 10 ┃
┣━━━━╋━━━━╋━━━━┫  ​   ┣━━━━┫  ​   ┣━━━━┫
┃ -1 ┃ 12 ┃ -2 ┃  *  ┃ x2 ┃  =  ┃  9 ┃
┣━━━━╋━━━━╋━━━━┫     ┣━━━━┫     ┣━━━━┫
┃ -1 ┃ -2 ┃ 12 ┃     ┃ x3 ┃     ┃ 14 ┃
┗━━━━┻━━━━┻━━━━┛     ┗━━━━┛     ┗━━━━┛


In [11]:
a = ""
for i in range(len(matrizDosCoeficientes)):
    pivo = matrizDosCoeficientes[i][i]
    a = f'|a_{{{str(i+1)+str(i+1)}}}| >'
    b = f'|{matrizDosCoeficientes[i][i]}| >'
    c = abs(matrizDosCoeficientes[i][i])
    c1 = 0
    for j in range(len(matrizDosCoeficientes[0])):
        if i != j:
            a = a + f" |a_{{{str(i+1)+str(j+1)}}}|+"
            b = b + f'|{matrizDosCoeficientes[i][j]}|+'
            c1 = c1 + abs(matrizDosCoeficientes[i][j])
    a = a[:-1]
    b = b[:-1]
    resultado = f'{a} \u2192 \hspace{{0.5cm}} {b} \hspace{{0.5cm}} {c}{" < " + str(c1) if c < c1 else " > " + str(c1)}'
    print_latex(resultado)
    if '<' in resultado:
        print('a condição de pivo maior que a soma dos elementos da mesma linha não foi satisfeita. selecione novos elementos!')
        raise SystemExit("")
    else:
        continue







<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

In [12]:
for i in range(len(matrizDosCoeficientes)):
    pivo = matrizDosCoeficientes[i][i]
    matrizDosCoeficientes[i][i] = 0
    for j in range(len(matrizDosCoeficientes[0])):
        if i!=j:
            matrizDosCoeficientes[i][j] = matrizDosCoeficientes[i][j]/pivo
    matrizResultante[i] = matrizResultante[i]/pivo


tabela = [[tabulate(matrizDosCoeficientes, tablefmt='heavy_grid'),tabulate(caracterEspace1,tablefmt='plain'), tabulate(matrizDasVariaveis, tablefmt='heavy_grid'), tabulate(caracterEspace2,tablefmt='plain'), tabulate(matrizResultante, tablefmt='heavy_grid')]]
print(tabulate(tabela, headers=[], tablefmt='plain'))



┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┓  ​   ┏━━━━┓  ​   ┏━━━━━━━━━━┓
┃  0         ┃ -0.0833333 ┃ -0.0833333 ┃  ​   ┃ x1 ┃  ​   ┃ 0.833333 ┃
┣━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━┫  ​   ┣━━━━┫  ​   ┣━━━━━━━━━━┫
┃ -0.0833333 ┃  0         ┃ -0.166667  ┃  *  ┃ x2 ┃  =  ┃ 0.75     ┃
┣━━━━━━━━━━━━╋━━━━━━━━━━━━╋━━━━━━━━━━━━┫     ┣━━━━┫     ┣━━━━━━━━━━┫
┃ -0.0833333 ┃ -0.166667  ┃  0         ┃     ┃ x3 ┃     ┃ 1.16667  ┃
┗━━━━━━━━━━━━┻━━━━━━━━━━━━┻━━━━━━━━━━━━┛     ┗━━━━┛     ┗━━━━━━━━━━┛


In [13]:
#Aplicando a equação de jacobi

#atribuindo valor inicial para as variaveis: x1 = x2 = x3 = 0
parcial = 0
ant = 0
v_anterior = np.zeros(len(matrizDosCoeficientes))
tol_ant = 1
resultadox = []
matriz_tol = np.random.random(len(matrizDosCoeficientes))
r = np.random.random(len(matrizDosCoeficientes))
TABELADESGRAÇADA = []
for i in range(len(matrizDosCoeficientes)):
    matrizDasVariaveis[i] = 0
while ant!=30:
    for i in range(len(matrizDosCoeficientes)):
        parcial = matrizResultante[i]
        print(f'{parcial} ',end =" ")
        for j in range(len(matrizDosCoeficientes[0])):
            if i != j:
                print(f'- ({matrizDosCoeficientes[i][j]}) * ({matrizDasVariaveis[j]})',end=' ')
                parcial = parcial - matrizDosCoeficientes[i][j]*matrizDasVariaveis[j]

        print(f' = {parcial}',end=" ") #mostra o valor do xi atual encontrado
        print('\n\n')

        matriz_tol[i] = abs((parcial-v_anterior[i])/parcial)

        print(f"\n\n| ({parcial} - {v_anterior[i]})/{parcial} |\n\n")
        if abs((parcial-v_anterior[i])/parcial) <= 0.0002:
            r[i] = matriz_tol[i]
            resultadox.append(v_anterior[i])
            print(f'\n\n\n{r}\n\n\n')
            print(resultadox)
        else:
            r[i] = matriz_tol[i]
            print(f'\n\n\n{matriz_tol}\n\n\n')
            resultadox.append(parcial)
            v_anterior[i] = parcial
            print(resultadox)
        TABELADESGRAÇADA.append([f'x{i+1}',parcial,r[i]])

    if all(elemento < 0.0002 for elemento in r):
      break
    else:
      pass
    for i in range(len(matrizDasVariaveis)):
        matrizDasVariaveis[i] = resultadox[i]
    ant = ant +1
    print(f'\n{ant}\n')
    resultadox = []


[0.83333333]  - (-0.08333333333333333) * (0) - (-0.08333333333333333) * (0)  = [0.83333333] 




| ([0.83333333] - 0.0)/[0.83333333] |





[1.         0.39949482 0.58081492]



[array([0.83333333])]
[0.75]  - (-0.08333333333333333) * (0) - (-0.16666666666666666) * (0)  = [0.75] 




| ([0.75] - 0.0)/[0.75] |





[1.         1.         0.58081492]



[array([0.83333333]), array([0.75])]
[1.16666667]  - (-0.08333333333333333) * (0) - (-0.16666666666666666) * (0)  = [1.16666667] 




| ([1.16666667] - 0.0)/[1.16666667] |





[1. 1. 1.]



[array([0.83333333]), array([0.75]), array([1.16666667])]

1

[0.83333333]  - (-0.08333333333333333) * ([0.75]) - (-0.08333333333333333) * ([1.16666667])  = [0.99305556] 




| ([0.99305556] - 0.8333333333333334)/[0.99305556] |





[0.16083916 1.         1.        ]



[array([0.99305556])]
[0.75]  - (-0.08333333333333333) * ([0.83333333]) - (-0.16666666666666666) * ([1.16666667])  = [1.01388889] 




| ([1.01388889] - 0.75)/[1.01388889] |





[0.16

In [14]:
numeros = [i + 1 for i in range(len(TABELADESGRAÇADA) // len(matrizDasVariaveis)) for _ in range(len(matrizDasVariaveis))]
for i, numero in enumerate(numeros):
    TABELADESGRAÇADA[i].insert(0, f'{numero}ª')
df = pd.DataFrame(TABELADESGRAÇADA)
for i in range(len(matrizDasVariaveis), len(TABELADESGRAÇADA) + (len(TABELADESGRAÇADA)//len(matrizDasVariaveis))+1, len(matrizDasVariaveis)+1):
    TABELADESGRAÇADA.insert(i, ["---------"] * len(TABELADESGRAÇADA[0]))
print(tabulate(TABELADESGRAÇADA,tablefmt='heavy_grid',headers=['iteração i','x_i+n','Resultado',f'tolerância(<={0.0002})']))

┏━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ iteração i   ┃ x_i+n     ┃ Resultado    ┃ tolerância(<=0.0002)   ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ 1ª           ┃ x1        ┃ [0.83333333] ┃ 1.0                    ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ 1ª           ┃ x2        ┃ [0.75]       ┃ 1.0                    ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ 1ª           ┃ x3        ┃ [1.16666667] ┃ 1.0                    ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ ---------    ┃ --------- ┃ ---------    ┃ ---------              ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ 2ª           ┃ x1        ┃ [0.99305556] ┃ 0.16083916083916083    ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━━━━━━━━━╋━━━━━━━━━━━━━━━━━━━━━━━━┫
┃ 2ª           ┃ x2        ┃ [1.01388889] ┃ 0.2602739726027397     ┃
┣━━━━━━━━━━━━━━╋━━━━━━━━━━━╋━━━━━━